# Generated by Django 2.2 on 2019-04-24 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Created_By', to='taskr.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='assignedTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assigned_To', to='taskr.User'),
        ),
    ]
