# Generated by Django 2.2 on 2019-04-24 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskr', '0003_auto_20190424_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 1, 12, 0, 20, 883543)),
        ),
    ]
