# Generated by Django 2.2 on 2019-04-28 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskr', '0005_auto_20190424_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 5, 14, 54, 18, 641472)),
        ),
    ]
